-- Crear tabla QR_INFO
DROP TABLE IF EXISTS QR_INFO;
CREATE TABLE QR_INFO (
    ID INT NOT NULL AUTO_INCREMENT,
    QR_NAME VARCHAR(255) NOT NULL,
    QR_SIZE VARCHAR(255) NOT NULL,
    QR_IMAGE LONGBLOB NOT NULL,
    PRIMARY KEY (ID)
);